#DESAFIO 24: CRIE UM PROGRAMA QUE LEIA O NOME DE UMA CIDADE E DIGA SE ELA COMEÇA OU NÃO COM O NOME SANTO.


cid = str(input('em que cidade vc nasceu?')).strip()
print (cid[:5].upper() == 'SANTO')


'''MAIS UMA VEZ O .strp() É UTILIZADO PRA ELIMINAR OS ESPAÇOS, JÁ O .upper() É PRA COLOCAR AS LETRAS EM MAIUSCULOS,
JÁ O [:5] É PRA SABER A CIDADE COMEÇA COM A PALAVRA SANTO,JÁ O == 'SANTO') É PRA IDENTICAR O NOME DA CIDADE,
NO CASO: SANTO'''
